import { config } from 'dotenv';
config();

import mongoose from 'mongoose';
import { env } from './config/env';
import Admin from './models/Admin';
import Service from './models/Service';
import Project from './models/Project';
import BlogPost from './models/BlogPost';
import Testimonial from './models/Testimonial';
import Client from './models/Client';
import PricingPlan from './models/PricingPlan';
import TeamMember from './models/TeamMember';
import JobPosting from './models/JobPosting';
import SiteSettings from './models/SiteSettings';

async function seed() {
  await mongoose.connect(env.MONGODB_URI);
  console.log('Connected to MongoDB');

  // Clear existing data
  await Promise.all([
    Admin.deleteMany({}), Service.deleteMany({}), Project.deleteMany({}),
    BlogPost.deleteMany({}), Testimonial.deleteMany({}), Client.deleteMany({}),
    PricingPlan.deleteMany({}), TeamMember.deleteMany({}), JobPosting.deleteMany({}),
    SiteSettings.deleteMany({}),
  ]);
  console.log('Cleared existing data');

  // Admin
  await Admin.create({
    name: 'Admin',
    email: 'admin@genmash.com',
    password: 'admin123456',
    role: 'super_admin',
  });
  console.log('Admin created (admin@genmash.com / admin123456)');

  // Services
  const services = [
    { title: 'Website Development', icon: 'Globe', shortDescription: 'Modern, responsive websites built with React, Next.js, and cutting-edge technologies for optimal performance and SEO.', fullDescription: 'We build fast, responsive, SEO-optimized websites using modern frameworks like React, Next.js, and Vue.js. From landing pages to complex web applications, our websites are designed to convert visitors into customers while providing exceptional user experiences across all devices.', technologies: ['React', 'Next.js', 'Vue.js', 'TypeScript', 'Tailwind CSS', 'Node.js'], process: [{step:1,title:'Discovery & Planning',description:'Understanding your goals, target audience, and requirements.'},{step:2,title:'UI/UX Design',description:'Wireframes, mockups, and interactive prototypes.'},{step:3,title:'Development',description:'Clean, maintainable code with modern best practices.'},{step:4,title:'Testing & QA',description:'Cross-browser, responsive, and performance testing.'},{step:5,title:'Deployment',description:'Production deployment with CI/CD pipelines.'},{step:6,title:'Support',description:'Ongoing updates, monitoring, and optimization.'}], timeline: '4-12 weeks', startingPrice: '$2,000', faqs: [{question:'What technologies do you use?',answer:'We primarily use React/Next.js for frontend and Node.js for backend, but we adapt our stack to your project needs.'},{question:'Do you provide hosting?',answer:'Yes, we can deploy on Vercel, AWS, or your preferred hosting platform.'},{question:'Is the website SEO-friendly?',answer:'Absolutely. All our websites are built with SEO best practices including SSR/SSG, meta tags, and structured data.'}], isActive: true, order: 1 },
    { title: 'Website Maintenance', icon: 'Wrench', shortDescription: 'Ongoing support, updates, security patches, and performance optimization to keep your website running smoothly.', fullDescription: 'Keep your website secure, fast, and up-to-date with our comprehensive maintenance services. We handle updates, security patches, performance monitoring, and bug fixes so you can focus on growing your business.', technologies: ['React', 'Node.js', 'WordPress', 'Analytics'], process: [{step:1,title:'Audit',description:'Complete website health assessment.'},{step:2,title:'Plan',description:'Prioritized maintenance schedule.'},{step:3,title:'Execute',description:'Regular updates and patches.'},{step:4,title:'Monitor',description:'24/7 uptime and performance monitoring.'}], timeline: 'Ongoing', startingPrice: '$200/month', faqs: [{question:'What does maintenance include?',answer:'Security updates, bug fixes, performance optimization, content updates, and uptime monitoring.'}], isActive: true, order: 2 },
    { title: 'Website Renovation', icon: 'RefreshCw', shortDescription: 'Redesign and modernize your existing website with better UX, faster performance, and responsive design.', fullDescription: 'Transform your outdated website into a modern, high-performing digital asset. We redesign with fresh UI/UX, improve performance, ensure mobile responsiveness, and add new features while preserving your SEO rankings.', technologies: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript'], process: [{step:1,title:'Audit Current Site',description:'Analyze existing performance, UX, and SEO.'},{step:2,title:'Redesign',description:'Modern UI/UX with your brand guidelines.'},{step:3,title:'Develop',description:'Build the new version with improved stack.'},{step:4,title:'Migrate',description:'Seamless transition with zero downtime.'}], timeline: '3-8 weeks', startingPrice: '$1,500', faqs: [], isActive: true, order: 3 },
    { title: 'Mobile App Development', icon: 'Smartphone', shortDescription: 'Native and cross-platform mobile apps for iOS and Android using React Native and Flutter.', fullDescription: 'We create beautiful, high-performance mobile applications for iOS and Android. Using React Native and Flutter, we deliver cross-platform apps that feel truly native while reducing development time and cost.', technologies: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase', 'Expo'], process: [{step:1,title:'Requirements',description:'Define features, user stories, and technical requirements.'},{step:2,title:'Design',description:'Mobile-first design with platform-specific guidelines.'},{step:3,title:'Development',description:'Agile sprints with regular demos.'},{step:4,title:'Testing',description:'Device testing and performance optimization.'},{step:5,title:'Launch',description:'App Store and Google Play submission.'},{step:6,title:'Support',description:'Post-launch maintenance and updates.'}], timeline: '8-20 weeks', startingPrice: '$5,000', faqs: [{question:'Cross-platform or native?',answer:'We recommend cross-platform (React Native/Flutter) for most projects. Native is best for performance-critical apps.'},{question:'Do you handle app store publishing?',answer:'Yes, we manage the entire submission process for both platforms.'}], isActive: true, order: 4 },
    { title: 'AI/ML Development', icon: 'Brain', shortDescription: 'Custom AI solutions including machine learning models, NLP, computer vision, and predictive analytics.', fullDescription: 'We build intelligent AI solutions that transform your business. From custom machine learning models to natural language processing and computer vision, we leverage cutting-edge AI to automate processes and generate insights.', technologies: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI', 'LangChain', 'Hugging Face', 'FastAPI'], process: [{step:1,title:'Data Assessment',description:'Evaluate your data and define objectives.'},{step:2,title:'Model Development',description:'Train, test, and optimize ML models.'},{step:3,title:'Integration',description:'Integrate models into your systems.'},{step:4,title:'Deployment',description:'Deploy with monitoring and auto-scaling.'},{step:5,title:'Iteration',description:'Continuous improvement based on real-world performance.'}], timeline: '6-16 weeks', startingPrice: '$8,000', faqs: [{question:'What kind of AI solutions do you build?',answer:'Chatbots, recommendation systems, predictive models, NLP tools, computer vision apps, and custom LLM integrations.'}], isActive: true, order: 5 },
    { title: 'AI Agents & Automation', icon: 'Bot', shortDescription: 'Intelligent AI agents and workflow automation systems that reduce manual work and boost efficiency.', fullDescription: 'Build smart AI agents that handle complex tasks autonomously. We create workflow automation systems, multi-agent architectures, and intelligent process automation that reduce operational costs and boost productivity.', technologies: ['Python', 'LangChain', 'LangGraph', 'CrewAI', 'n8n', 'OpenAI'], process: [{step:1,title:'Process Audit',description:'Map workflows and identify automation opportunities.'},{step:2,title:'Agent Design',description:'Design agent architecture and capabilities.'},{step:3,title:'Build & Train',description:'Develop and fine-tune AI agents.'},{step:4,title:'Deploy',description:'Production deployment with monitoring.'}], timeline: '4-12 weeks', startingPrice: '$5,000', faqs: [], isActive: true, order: 6 },
    { title: 'Chatbot Development', icon: 'MessageSquare', shortDescription: 'Smart chatbots for customer support, lead generation, and engagement powered by LLMs and NLP.', fullDescription: 'Build intelligent chatbots that understand natural language, provide accurate responses, and integrate seamlessly with your existing systems. From customer support to lead qualification, our chatbots deliver real business value.', technologies: ['OpenAI', 'LangChain', 'Python', 'Node.js', 'Dialogflow'], process: [{step:1,title:'Requirements',description:'Define use cases and conversation flows.'},{step:2,title:'Build',description:'Develop chatbot with NLP capabilities.'},{step:3,title:'Train',description:'Train on your domain data.'},{step:4,title:'Deploy',description:'Integrate with your website/platform.'}], timeline: '3-8 weeks', startingPrice: '$3,000', faqs: [], isActive: true, order: 7 },
    { title: 'Game Development', icon: 'Gamepad2', shortDescription: 'Engaging 2D/3D games for mobile, desktop, and web using Unity and Unreal Engine.', fullDescription: 'Create immersive gaming experiences with cutting-edge graphics and engaging gameplay. We build 2D and 3D games for mobile, desktop, and web platforms using industry-standard engines.', technologies: ['Unity', 'Unreal Engine', 'Godot', 'C#', 'C++'], process: [{step:1,title:'Concept',description:'Game design document and mechanics.'},{step:2,title:'Art & Assets',description:'Visual design, 3D models, animations.'},{step:3,title:'Development',description:'Core mechanics, levels, and features.'},{step:4,title:'Testing',description:'QA, performance, and playtesting.'},{step:5,title:'Launch',description:'Publishing to target platforms.'}], timeline: '12-24 weeks', startingPrice: '$10,000', faqs: [], isActive: true, order: 8 },
    { title: 'Desktop Applications', icon: 'Monitor', shortDescription: 'Cross-platform desktop software with Electron, .NET, and Java for Windows, macOS, and Linux.', fullDescription: 'Build powerful desktop applications that run on Windows, macOS, and Linux. We use Electron for cross-platform apps and .NET/Java for platform-specific solutions.', technologies: ['Electron', 'React', '.NET', 'Java', 'SQLite'], process: [{step:1,title:'Requirements',description:'Define features and platform targets.'},{step:2,title:'Design',description:'Desktop-optimized UI/UX.'},{step:3,title:'Develop',description:'Build with native performance.'},{step:4,title:'Package',description:'Installer and auto-update setup.'}], timeline: '8-16 weeks', startingPrice: '$5,000', faqs: [], isActive: true, order: 9 },
    { title: 'Enterprise Software', icon: 'Building2', shortDescription: 'Scalable enterprise solutions including ERP, CRM, and custom business management systems.', fullDescription: 'Build enterprise-grade software solutions that streamline operations and drive efficiency. From ERP and CRM systems to custom business tools, we deliver robust, scalable applications.', technologies: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'AWS'], process: [{step:1,title:'Discovery',description:'Business process analysis.'},{step:2,title:'Architecture',description:'Scalable system design.'},{step:3,title:'Development',description:'Modular, iterative development.'},{step:4,title:'Testing',description:'Enterprise QA and security testing.'},{step:5,title:'Deployment',description:'Staged rollout with training.'}], timeline: '16-32 weeks', startingPrice: '$15,000', faqs: [], isActive: true, order: 10 },
    { title: 'Cloud & DevOps', icon: 'Cloud', shortDescription: 'Cloud infrastructure, CI/CD pipelines, containerization, and DevOps practices on AWS, GCP, and Azure.', fullDescription: 'Optimize your infrastructure with cloud-native solutions and DevOps best practices. We set up scalable, secure, cost-effective cloud environments with automated deployments.', technologies: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions'], process: [{step:1,title:'Audit',description:'Current infrastructure assessment.'},{step:2,title:'Plan',description:'Cloud strategy and architecture.'},{step:3,title:'Migrate',description:'Zero-downtime cloud migration.'},{step:4,title:'Automate',description:'CI/CD pipelines and monitoring.'}], timeline: '2-8 weeks', startingPrice: '$3,000', faqs: [], isActive: true, order: 11 },
    { title: 'UI/UX Design', icon: 'Palette', shortDescription: 'User-centered design with wireframing, prototyping, and beautiful interfaces that convert visitors.', fullDescription: 'Create intuitive, visually stunning interfaces that delight users and drive conversions. Our design process is research-driven and user-centered.', technologies: ['Figma', 'Adobe XD', 'Framer', 'Tailwind CSS'], process: [{step:1,title:'Research',description:'User research and competitive analysis.'},{step:2,title:'Wireframes',description:'Low-fidelity structure and flow.'},{step:3,title:'Mockups',description:'High-fidelity visual design.'},{step:4,title:'Prototype',description:'Interactive, testable prototype.'},{step:5,title:'Handoff',description:'Developer-ready design specs.'}], timeline: '2-6 weeks', startingPrice: '$2,000', faqs: [], isActive: true, order: 12 },
    { title: 'API Development', icon: 'Code', shortDescription: 'RESTful and GraphQL APIs, third-party integrations, and microservices architecture.', fullDescription: 'Design and build robust APIs that power your applications. We create scalable REST and GraphQL APIs, integrate third-party services, and architect microservices systems.', technologies: ['Node.js', 'Express', 'FastAPI', 'GraphQL', 'PostgreSQL', 'Redis'], process: [{step:1,title:'Design',description:'API architecture and documentation.'},{step:2,title:'Build',description:'Implement endpoints and business logic.'},{step:3,title:'Test',description:'Automated testing and load testing.'},{step:4,title:'Deploy',description:'Production deployment with monitoring.'}], timeline: '3-10 weeks', startingPrice: '$3,000', faqs: [], isActive: true, order: 13 },
  ];
  for (const s of services) await Service.create(s);
  console.log(`${services.length} services seeded`);

  // Projects
  const projects = [
    { title: 'E-Commerce Platform', clientName: 'RetailMax', projectType: 'web', description: 'Full-featured e-commerce platform with real-time inventory, payment processing, and AI-powered product recommendations.', technologies: ['Next.js', 'Node.js', 'MongoDB', 'Stripe', 'Redis'], isVisible: true, isFeatured: true, order: 1, caseStudy: { overview: 'Built a comprehensive e-commerce platform handling thousands of daily transactions with AI-powered product recommendations.', problem: 'RetailMax was using an outdated system with 8s page loads, poor mobile experience, and no personalization.', solution: 'Built a Next.js platform with SSR for instant loads, responsive design, and an AI recommendation engine.', features: ['Real-time inventory tracking', 'AI product recommendations', 'Multi-payment gateway', 'Admin dashboard', 'Mobile-responsive checkout', 'Order tracking'], architecture: 'Microservices with Next.js frontend, Node.js API, MongoDB database, Redis cache', screenshots: [], results: 'Dramatically improved performance and user engagement across all metrics.', metrics: [{label:'Page Load Time',value:'1.2s (from 8s)'},{label:'Conversion Rate',value:'+42%'},{label:'Avg Order Value',value:'+35%'},{label:'Mobile Traffic',value:'+60%'}], liveUrl: 'https://retailmax.example.com', clientTestimonial: 'GenMash delivered beyond our expectations.' }},
    { title: 'Healthcare Mobile App', clientName: 'MediCare Plus', projectType: 'mobile', description: 'Telemedicine app with video consultations, appointment scheduling, and health record management.', technologies: ['React Native', 'Firebase', 'WebRTC', 'Node.js'], isVisible: true, isFeatured: true, order: 2, caseStudy: { overview: 'Telemedicine platform connecting patients with doctors through video consultations.', problem: 'Patients had no way to consult doctors remotely, leading to missed appointments and delayed care.', solution: 'Built a HIPAA-compliant mobile app with video calling, scheduling, and digital health records.', features: ['Video consultations', 'Appointment scheduling', 'Health records', 'Prescription management', 'Push notifications', 'Payment integration'], screenshots: [], results: 'Enabled remote healthcare access for thousands of patients.', metrics: [{label:'Active Users',value:'10,000+'},{label:'Consultations',value:'5,000/month'},{label:'App Rating',value:'4.8/5'}], liveUrl: '', clientTestimonial: '' }},
    { title: 'AI Customer Support Bot', clientName: 'TechCorp', projectType: 'ai', description: 'Intelligent chatbot handling 80% of customer queries automatically using NLP and knowledge base integration.', technologies: ['Python', 'LangChain', 'OpenAI', 'FastAPI', 'Redis'], isVisible: true, isFeatured: true, order: 3, caseStudy: { overview: 'AI-powered customer support chatbot that resolves most queries without human intervention.', problem: 'TechCorp support team was overwhelmed with repetitive queries, leading to long response times.', solution: 'Built an intelligent chatbot using LLMs with RAG over the company knowledge base.', features: ['Natural language understanding', 'Knowledge base integration', 'Escalation to human agents', 'Multi-language support', 'Analytics dashboard'], screenshots: [], results: 'Dramatically reduced support workload and improved response times.', metrics: [{label:'Auto-Resolution',value:'80%'},{label:'Response Time',value:'<5 seconds'},{label:'Cost Savings',value:'60%'},{label:'CSAT Score',value:'4.5/5'}], liveUrl: '', clientTestimonial: '' }},
    { title: 'Logistics Dashboard', clientName: 'LogiFlow', projectType: 'web', description: 'Real-time fleet tracking, route optimization, and delivery management dashboard.', technologies: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'Socket.io'], isVisible: true, isFeatured: false, order: 4, caseStudy: { overview: 'Real-time logistics management platform for fleet tracking and delivery optimization.', problem: 'Manual tracking of 200+ vehicles with no visibility into delivery status.', solution: 'Built a real-time dashboard with GPS tracking, route optimization, and automated notifications.', features: ['Real-time GPS tracking', 'Route optimization', 'Delivery status updates', 'Driver management', 'Analytics reports'], screenshots: [], results: 'Improved delivery efficiency and customer satisfaction.', metrics: [{label:'Delivery Time',value:'-25%'},{label:'Fuel Costs',value:'-15%'},{label:'On-time Rate',value:'96%'}], liveUrl: '', clientTestimonial: '' }},
    { title: 'Fitness Tracking App', clientName: 'FitLife', projectType: 'mobile', description: 'Workout tracking, nutrition planning, and progress analytics with wearable device integration.', technologies: ['Flutter', 'Firebase', 'TensorFlow Lite', 'Node.js'], isVisible: true, isFeatured: false, order: 5, caseStudy: { overview: 'Comprehensive fitness app with workout tracking, nutrition, and AI-powered coaching.', problem: 'Users needed an all-in-one fitness solution that integrates with wearable devices.', solution: 'Built a cross-platform app with AI coaching, wearable integration, and social features.', features: ['Workout tracking', 'Nutrition planning', 'Progress analytics', 'Wearable integration', 'AI coaching', 'Social challenges'], screenshots: [], results: 'High user engagement and retention.', metrics: [{label:'Downloads',value:'50,000+'},{label:'Daily Active',value:'12,000'},{label:'Retention',value:'68%'}], liveUrl: '', clientTestimonial: '' }},
    { title: 'Invoice Automation System', clientName: 'FinPro', projectType: 'automation', description: 'Automated invoice processing with OCR, approval workflows, and accounting integration.', technologies: ['Python', 'n8n', 'OpenAI', 'PostgreSQL', 'React'], isVisible: true, isFeatured: false, order: 6, caseStudy: { overview: 'End-to-end invoice processing automation for a financial services company.', problem: 'Manual invoice processing took 15 minutes per invoice with frequent errors.', solution: 'Built an OCR-powered system with automated data extraction, validation, and approval workflows.', features: ['OCR text extraction', 'Automated data validation', 'Approval workflows', 'Accounting integration', 'Error reporting'], screenshots: [], results: 'Massive time savings and error reduction.', metrics: [{label:'Processing Time',value:'2 min (from 15)'},{label:'Error Rate',value:'-90%'},{label:'Cost Savings',value:'70%'}], liveUrl: '', clientTestimonial: '' }},
    { title: 'E-Learning Platform', clientName: 'EduLearn Global', projectType: 'web', description: 'Interactive online learning platform with live classes, quizzes, and progress tracking.', technologies: ['Next.js', 'Node.js', 'MongoDB', 'WebRTC', 'Stripe'], isVisible: true, isFeatured: true, order: 7, caseStudy: { overview: 'Full-featured e-learning platform with live classes and interactive content.', problem: 'EduLearn needed to transition from in-person to online education during rapid growth.', solution: 'Built a scalable platform with live video classes, interactive quizzes, and progress tracking.', features: ['Live video classes', 'Interactive quizzes', 'Progress tracking', 'Certificate generation', 'Payment integration', 'Admin dashboard'], screenshots: [], results: 'Successfully scaled online education.', metrics: [{label:'Students',value:'25,000+'},{label:'Courses',value:'150+'},{label:'Completion',value:'78%'}], liveUrl: '', clientTestimonial: '' }},
    { title: 'Inventory Management', clientName: 'StockPro', projectType: 'desktop', description: 'Desktop inventory system with barcode scanning, stock alerts, and multi-warehouse support.', technologies: ['Electron', 'React', 'SQLite', 'Node.js'], isVisible: true, isFeatured: false, order: 8, caseStudy: { overview: 'Desktop inventory management system for multi-warehouse operations.', problem: 'Manual inventory tracking across 5 warehouses with frequent stock discrepancies.', solution: 'Built a desktop app with barcode scanning, real-time sync, and automated alerts.', features: ['Barcode scanning', 'Multi-warehouse support', 'Stock alerts', 'Reports & analytics', 'Auto-sync'], screenshots: [], results: 'Eliminated stock discrepancies and improved efficiency.', metrics: [{label:'Accuracy',value:'99.5%'},{label:'Time Saved',value:'60%'},{label:'Stock Loss',value:'-85%'}], liveUrl: '', clientTestimonial: '' }},
  ];
  for (const p of projects) await Project.create(p);
  console.log(`${projects.length} projects seeded`);

  // Blog Posts
  const blogPosts = [
    { title: 'How to Choose the Right Tech Stack for Your Startup', excerpt: 'A comprehensive guide to selecting the perfect technology stack for your startup based on goals, budget, and timeline.', content: '<p>Choosing the right technology stack is one of the most critical decisions for any startup. The wrong choice can lead to scalability issues, higher costs, and longer development times.</p><h2>Understanding Your Requirements</h2><p>Before diving into specific technologies, understand your project requirements. Consider expected traffic, real-time needs, SEO requirements, and your team\'s expertise.</p><h2>Frontend Frameworks</h2><p>For modern web apps, React and Next.js remain top choices. React provides robust component architecture, while Next.js adds SSR, SSG, and API routes.</p><h2>Backend Considerations</h2><p>Node.js with Express remains our go-to for JavaScript consistency. For AI-heavy projects, Python with FastAPI offers excellent ML library support.</p><h2>Key Takeaways</h2><ul><li>Start with requirements, not technology</li><li>Consider team expertise</li><li>Think about long-term maintainability</li><li>Don\'t over-engineer for scale you don\'t have yet</li></ul>', featuredImage: '', author: { name: 'Hariom Malviya', avatar: '', bio: 'Founder & CEO at GenMash' }, category: 'Engineering', tags: ['React', 'Next.js', 'Node.js', 'Tech Stack'], status: 'published' as const, publishedAt: new Date('2025-12-15') },
    { title: 'The Rise of AI Agents in Business Automation', excerpt: 'Explore how AI agents are revolutionizing business processes by automating complex workflows and decision-making.', content: '<p>AI agents are transforming how businesses operate by automating complex, multi-step workflows that previously required human intervention.</p><h2>What Are AI Agents?</h2><p>AI agents are autonomous systems that can perceive their environment, make decisions, and take actions to achieve specific goals.</p><h2>Business Applications</h2><p>From customer support to data processing, AI agents are being deployed across industries to handle repetitive tasks, make decisions, and even collaborate with other agents.</p><h2>Getting Started</h2><p>Start small with a single automation use case, measure ROI, then expand. The key is identifying processes that are repetitive, rule-based, and high-volume.</p>', featuredImage: '', author: { name: 'Srishti Doshi', avatar: '', bio: 'Co-Founder & CTO at GenMash' }, category: 'AI', tags: ['AI Agents', 'Automation', 'LangChain', 'Business'], status: 'published' as const, publishedAt: new Date('2025-11-28') },
    { title: 'Next.js vs React: When to Use What', excerpt: 'Understand the key differences between Next.js and React, and learn when to use each framework.', content: '<p>React and Next.js are both powerful tools, but they serve different purposes. Understanding when to use each is crucial for project success.</p><h2>React (SPA)</h2><p>Best for dashboards, admin panels, and apps where SEO isn\'t critical. Full client-side rendering with maximum flexibility.</p><h2>Next.js (Full Framework)</h2><p>Best for marketing sites, e-commerce, blogs, and any app where SEO matters. Provides SSR, SSG, API routes, and optimized performance out of the box.</p><h2>Our Recommendation</h2><p>For most new projects, we recommend Next.js. It gives you everything React offers plus server-side capabilities, file-based routing, and built-in optimization.</p>', featuredImage: '', author: { name: 'Hariom Malviya', avatar: '', bio: 'Founder & CEO at GenMash' }, category: 'Engineering', tags: ['Next.js', 'React', 'Frontend'], status: 'published' as const, publishedAt: new Date('2025-11-10') },
    { title: 'Building Scalable APIs with Node.js', excerpt: 'Best practices for building production-ready, scalable REST APIs using Node.js, Express, and MongoDB.', content: '<p>Building APIs that can handle growth requires careful architecture decisions from day one.</p><h2>Project Structure</h2><p>Use a layered architecture: routes → controllers → services → models. This separation makes testing and maintenance much easier.</p><h2>Error Handling</h2><p>Implement a global error handler. Catch async errors properly. Return consistent error response formats.</p><h2>Performance</h2><p>Use database indexes, implement pagination, add caching where appropriate, and compress responses.</p>', featuredImage: '', author: { name: 'Ankit Patel', avatar: '', bio: 'Lead Developer at GenMash' }, category: 'Backend', tags: ['Node.js', 'Express', 'API', 'MongoDB'], status: 'published' as const, publishedAt: new Date('2025-10-20') },
    { title: '5 UX Design Principles Every Developer Should Know', excerpt: 'Essential UX design principles that help developers build more intuitive applications.', content: '<p>Great UX isn\'t just a designer\'s job. Developers who understand UX principles build better products.</p><h2>1. Consistency</h2><p>Use consistent patterns, colors, and interactions throughout your app.</p><h2>2. Feedback</h2><p>Every user action should have visible feedback — loading states, success messages, error indicators.</p><h2>3. Simplicity</h2><p>Remove unnecessary elements. Every component should serve a purpose.</p><h2>4. Accessibility</h2><p>Build for everyone — keyboard navigation, screen readers, sufficient contrast.</p><h2>5. Performance</h2><p>Speed is UX. A slow app is a bad app, no matter how beautiful it looks.</p>', featuredImage: '', author: { name: 'Priya Sharma', avatar: '', bio: 'UI/UX Designer at GenMash' }, category: 'Design', tags: ['UX', 'Design', 'Frontend', 'Accessibility'], status: 'published' as const, publishedAt: new Date('2025-10-05') },
    { title: 'Cloud Cost Optimization: A Practical Guide', excerpt: 'Strategies to reduce cloud spending on AWS and GCP without sacrificing performance.', content: '<p>Cloud costs can spiral out of control quickly. Here are practical strategies we use to keep costs in check.</p><h2>Right-Sizing</h2><p>Most instances are over-provisioned. Analyze actual usage and downsize where possible.</p><h2>Reserved Instances</h2><p>For predictable workloads, reserved instances can save 30-60% compared to on-demand pricing.</p><h2>Auto-Scaling</h2><p>Scale down during low-traffic periods. Don\'t pay for capacity you\'re not using.</p><h2>Storage Optimization</h2><p>Use lifecycle policies to move old data to cheaper storage tiers.</p>', featuredImage: '', author: { name: 'Rohan Gupta', avatar: '', bio: 'AI/ML Engineer at GenMash' }, category: 'DevOps', tags: ['AWS', 'Cloud', 'DevOps', 'Cost Optimization'], status: 'published' as const, publishedAt: new Date('2025-09-18') },
  ];
  for (const b of blogPosts) await BlogPost.create(b);
  console.log(`${blogPosts.length} blog posts seeded`);

  // Testimonials
  const testimonials = [
    { clientName: 'Rajesh Kumar', company: 'TechStart India', designation: 'CEO', review: 'GenMash delivered our e-commerce platform ahead of schedule. Their attention to detail and technical expertise is outstanding. The platform handles thousands of daily transactions flawlessly.', rating: 5, projectType: 'web', isFeatured: true, isVisible: true, date: new Date('2025-10-01') },
    { clientName: 'Sarah Mitchell', company: 'HealthBridge Solutions', designation: 'Product Manager', review: 'Working with GenMash on our healthcare app was fantastic. They understood our compliance requirements perfectly and built a HIPAA-compliant solution that our users love.', rating: 5, projectType: 'mobile', isFeatured: true, isVisible: true, date: new Date('2025-09-15') },
    { clientName: 'Amit Sharma', company: 'LogiFlow', designation: 'CTO', review: 'The AI automation system GenMash built reduced our manual processing time by 70%. Their team is highly skilled in AI/ML and delivered exactly what we needed.', rating: 5, projectType: 'ai', isFeatured: true, isVisible: true, date: new Date('2025-08-20') },
    { clientName: 'Emily Chen', company: 'EduLearn Global', designation: 'Founder', review: 'GenMash transformed our vision into a beautiful e-learning platform. The UI/UX is intuitive, the backend is rock-solid, and their post-launch support has been excellent.', rating: 4, projectType: 'web', isFeatured: false, isVisible: true, date: new Date('2025-07-10') },
    { clientName: 'David Brown', company: 'FinPro Solutions', designation: 'VP Engineering', review: 'Their expertise in Node.js and React is top-notch. The invoicing system they built handles our entire workflow seamlessly.', rating: 5, projectType: 'automation', isFeatured: false, isVisible: true, date: new Date('2025-06-25') },
    { clientName: 'Priya Patel', company: 'CloudNine', designation: 'CEO', review: 'We hired GenMash for our cloud migration and DevOps setup. Zero downtime migration and 40% cost reduction. Highly recommended.', rating: 5, projectType: 'web', isFeatured: true, isVisible: true, date: new Date('2025-05-15') },
    { clientName: 'Michael Torres', company: 'GameStudio', designation: 'Creative Director', review: 'The mobile game they developed exceeded our expectations. Great graphics, smooth performance, and delivered on time.', rating: 4, projectType: 'game', isFeatured: false, isVisible: true, date: new Date('2025-04-20') },
    { clientName: 'Neha Gupta', company: 'DataSense', designation: 'Data Lead', review: 'GenMash built a custom ML pipeline that processes our data 10x faster. Their AI team really knows their stuff.', rating: 5, projectType: 'ai', isFeatured: false, isVisible: true, date: new Date('2025-03-10') },
  ];
  await Testimonial.insertMany(testimonials);
  console.log(`${testimonials.length} testimonials seeded`);

  // Clients
  const clients = [
    { name: 'TechStart India', industry: 'E-commerce', projectType: 'web', isVisible: true, order: 1 },
    { name: 'HealthBridge Solutions', industry: 'Healthcare', projectType: 'mobile', isVisible: true, order: 2 },
    { name: 'LogiFlow', industry: 'Logistics', projectType: 'web', isVisible: true, order: 3 },
    { name: 'EduLearn Global', industry: 'Education', projectType: 'web', isVisible: true, order: 4 },
    { name: 'RetailMax', industry: 'Retail', projectType: 'web', isVisible: true, order: 5 },
    { name: 'CloudNine', industry: 'SaaS', projectType: 'web', isVisible: true, order: 6 },
    { name: 'DataSense Analytics', industry: 'Data Science', projectType: 'ai', isVisible: true, order: 7 },
    { name: 'FinPro Solutions', industry: 'FinTech', projectType: 'automation', isVisible: true, order: 8 },
    { name: 'GameStudio', industry: 'Gaming', projectType: 'game', isVisible: true, order: 9 },
    { name: 'StockPro', industry: 'Inventory', projectType: 'desktop', isVisible: true, order: 10 },
    { name: 'FitLife', industry: 'Health & Fitness', projectType: 'mobile', isVisible: true, order: 11 },
    { name: 'GreenEnergy Corp', industry: 'Energy', projectType: 'web', isVisible: true, order: 12 },
  ];
  await Client.insertMany(clients);
  console.log(`${clients.length} clients seeded`);

  // Pricing Plans
  const pricingPlans = [
    { name: 'Starter Website', icon: 'Globe', targetAudience: 'Landing pages, personal sites', startingPrice: '$500', features: [{text:'Up to 5 pages',included:true},{text:'Responsive design',included:true},{text:'Contact form',included:true},{text:'Basic SEO setup',included:true},{text:'CMS integration',included:false},{text:'Custom animations',included:false},{text:'Admin panel',included:false}], timeline: '1-2 weeks', isPopular: false, isActive: true, order: 1 },
    { name: 'Business Website', icon: 'Building2', targetAudience: 'SMBs, corporate sites', startingPrice: '$2,000', features: [{text:'Up to 15 pages',included:true},{text:'Responsive design',included:true},{text:'Advanced SEO',included:true},{text:'CMS / Admin panel',included:true},{text:'Blog system',included:true},{text:'Custom animations',included:true},{text:'Analytics integration',included:true}], timeline: '3-5 weeks', isPopular: true, isActive: true, order: 2 },
    { name: 'E-commerce', icon: 'ShoppingCart', targetAudience: 'Online stores', startingPrice: '$5,000', features: [{text:'Unlimited products',included:true},{text:'Payment integration',included:true},{text:'Inventory management',included:true},{text:'Order tracking',included:true},{text:'Admin dashboard',included:true},{text:'Email notifications',included:true},{text:'Customer accounts',included:true}], timeline: '6-10 weeks', isPopular: false, isActive: true, order: 3 },
    { name: 'Custom Web App', icon: 'Code', targetAudience: 'SaaS, dashboards, portals', startingPrice: '$8,000', features: [{text:'Custom architecture',included:true},{text:'User authentication',included:true},{text:'Role-based access',included:true},{text:'API development',included:true},{text:'Real-time features',included:true},{text:'Cloud deployment',included:true},{text:'CI/CD pipeline',included:true}], timeline: '8-16 weeks', isPopular: false, isActive: true, order: 4 },
    { name: 'Mobile App', icon: 'Smartphone', targetAudience: 'iOS/Android apps', startingPrice: '$5,000', features: [{text:'iOS & Android',included:true},{text:'Push notifications',included:true},{text:'Offline support',included:true},{text:'App Store submission',included:true},{text:'API integration',included:true},{text:'Analytics',included:true},{text:'Post-launch support',included:true}], timeline: '8-16 weeks', isPopular: false, isActive: true, order: 5 },
    { name: 'AI Solution', icon: 'Brain', targetAudience: 'ML models, AI integrations', startingPrice: '$8,000', features: [{text:'Custom AI model',included:true},{text:'Data processing',included:true},{text:'API integration',included:true},{text:'Dashboard',included:true},{text:'Model training',included:true},{text:'Deployment & scaling',included:true},{text:'Monitoring',included:true}], timeline: '6-16 weeks', isPopular: false, isActive: true, order: 6 },
    { name: 'Automation System', icon: 'Bot', targetAudience: 'Workflow automation', startingPrice: '$3,000', features: [{text:'Workflow design',included:true},{text:'API integrations',included:true},{text:'Email automation',included:true},{text:'Custom triggers',included:true},{text:'Dashboard',included:true},{text:'Error handling',included:true},{text:'Documentation',included:true}], timeline: '3-8 weeks', isPopular: false, isActive: true, order: 7 },
  ];
  await PricingPlan.insertMany(pricingPlans);
  console.log(`${pricingPlans.length} pricing plans seeded`);

  // Team Members
  const teamMembers = [
    { name: 'Hariom Malviya', role: 'Founder & CEO', bio: 'Full-stack developer with a passion for building scalable software solutions.', linkedin: 'https://linkedin.com/in/hariom-malviya', github: 'https://github.com/hariom', order: 1, isVisible: true },
    { name: 'Srishti Doshi', role: 'Co-Founder & CTO', bio: 'Expert in AI/ML and system architecture with a focus on innovative solutions.', linkedin: 'https://linkedin.com/in/srishti-doshi', github: 'https://github.com/Srishti-Doshi', order: 2, isVisible: true },
    { name: 'Ankit Patel', role: 'Lead Developer', bio: 'Experienced full-stack developer specializing in React and Node.js ecosystems.', linkedin: '', github: '', order: 3, isVisible: true },
    { name: 'Priya Sharma', role: 'UI/UX Designer', bio: 'Creative designer focused on building beautiful, user-centered interfaces.', linkedin: '', github: '', order: 4, isVisible: true },
    { name: 'Rohan Gupta', role: 'AI/ML Engineer', bio: 'Machine learning engineer with expertise in NLP, computer vision, and AI agents.', linkedin: '', github: '', order: 5, isVisible: true },
    { name: 'Neha Singh', role: 'Project Manager', bio: 'Agile project manager ensuring smooth delivery and client satisfaction.', linkedin: '', github: '', order: 6, isVisible: true },
  ];
  await TeamMember.insertMany(teamMembers);
  console.log(`${teamMembers.length} team members seeded`);

  // Job Postings
  const jobs = [
    { title: 'Senior Full Stack Developer', department: 'Engineering', location: 'hybrid' as const, experienceLevel: '3-5 years', jobType: 'full-time' as const, description: 'We\'re looking for a senior full-stack developer to lead projects and mentor junior developers. You\'ll work on exciting client projects using React, Next.js, and Node.js.', requirements: ['Strong proficiency in React and TypeScript','3+ years experience with Node.js and MongoDB','Understanding of RESTful API design','Experience with Git and CI/CD','Excellent problem-solving skills'], responsibilities: ['Design and develop web applications','Lead technical architecture decisions','Mentor junior developers','Participate in code reviews','Collaborate with designers and PMs'], perks: ['Remote-friendly','Health insurance','Learning budget','Flexible hours','Performance bonus'], isActive: true },
    { title: 'React Native Developer', department: 'Mobile', location: 'remote' as const, experienceLevel: '2-4 years', jobType: 'full-time' as const, description: 'Join our mobile team to build cross-platform apps with React Native. You\'ll work on healthcare, fitness, and e-commerce apps for global clients.', requirements: ['2+ years React Native experience','Understanding of mobile design patterns','Experience with Firebase/Supabase','Knowledge of app store deployment','Strong debugging skills'], responsibilities: ['Build cross-platform mobile apps','Optimize app performance','Integrate APIs and third-party SDKs','Write unit and integration tests','Collaborate with backend team'], perks: ['Fully remote','Health insurance','Latest hardware','Conference budget'], isActive: true },
    { title: 'AI/ML Engineer', department: 'AI', location: 'indore' as const, experienceLevel: '2-5 years', jobType: 'full-time' as const, description: 'Work on cutting-edge AI projects including chatbots, recommendation systems, and automation agents using LLMs and ML frameworks.', requirements: ['Strong Python skills','Experience with TensorFlow or PyTorch','Knowledge of NLP and LLMs','Understanding of MLOps practices','Problem-solving mindset'], responsibilities: ['Build and train ML models','Develop AI-powered applications','Integrate LLMs and AI APIs','Optimize model performance','Research new AI techniques'], perks: ['Health insurance','Learning budget','Innovation time','Team outings'], isActive: true },
    { title: 'UI/UX Designer', department: 'Design', location: 'remote' as const, experienceLevel: '1-3 years', jobType: 'full-time' as const, description: 'Design beautiful, intuitive interfaces for web and mobile applications. Work closely with developers and clients to deliver exceptional user experiences.', requirements: ['Proficiency in Figma','Understanding of design systems','Knowledge of web/mobile UX patterns','Basic understanding of HTML/CSS','Portfolio of previous work'], responsibilities: ['Create wireframes and prototypes','Design responsive UI components','Conduct user research','Build and maintain design systems','Collaborate with developers'], perks: ['Fully remote','Flexible hours','Design tool subscriptions','Learning budget'], isActive: true },
    { title: 'Frontend Developer Intern', department: 'Engineering', location: 'indore' as const, experienceLevel: '0-1 years', jobType: 'internship' as const, description: 'Kickstart your career in web development. Learn from experienced developers while working on real client projects using React and Next.js.', requirements: ['Basic knowledge of HTML, CSS, JavaScript','Familiarity with React (learning is OK)','Eagerness to learn','Good communication skills','Currently pursuing or recently completed CS degree'], responsibilities: ['Assist in building web applications','Learn React and Next.js','Fix bugs and write tests','Participate in daily standups','Complete assigned learning modules'], perks: ['Stipend','Certificate','Pre-placement offer opportunity','Mentorship'], isActive: true },
  ];
  for (const j of jobs) await JobPosting.create(j);
  console.log(`${jobs.length} job postings seeded`);

  // Site Settings
  await SiteSettings.create({
    companyName: 'GenMash Software Solutions',
    tagline: 'Transforming Ideas into Digital Reality',
    email: 'contact@genmash.com',
    phone: '+91 98765 43210',
    whatsapp: '+919876543210',
    address: 'Indore, Madhya Pradesh, India',
    socialLinks: { linkedin: 'https://linkedin.com/company/genmash', github: 'https://github.com/genmash', twitter: 'https://twitter.com/genmash', instagram: 'https://instagram.com/genmash' },
    seo: { defaultTitle: 'GenMash Software Solutions | Custom Software Development', defaultDescription: 'GenMash builds custom websites, mobile apps, AI solutions, and enterprise software. Based in Indore, serving clients worldwide.', ogImage: '' },
    officeHours: 'Mon-Fri, 10:00 AM - 7:00 PM IST',
  });
  console.log('Site settings seeded');

  console.log('\n✅ Database seeded successfully!');
  console.log('Admin login: admin@genmash.com / admin123456\n');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
